### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ghost** [cdein/python-radon#1]
Hello,
I'm running this on Windows. I have radon latest version from pip and all. The executable is configured well and I can use it manually no problem.
But I don't see anywhere how to use this. I think it's supposed to be shown in the status bar? But it doesn't.
I think a GIF showing at least example usage on the marketplace would be useful.

Ps. Code Lens is enabled in my settings.

**Comment by cdein** [comment]
Hello,
you should see a text entry in front of each function method or class, which tells you the rank (A-F) and the value of complexity. Additionally there is also an item in the status bar which shows the overall maintainability index and the according rank (A-C) of the source code.

I don't have a Windows system running, so I can't check. May you test to surround the absolute path to your radon executable file with double quotes in the configuration, e. g. "C:\users\cdein\bin\radon.exe" or \"C:\users\cdein\bin\radon.exe\" in the JSON configuration.

**Comment by cdein** [comment]
I've added a screenshot and a short description in the README.md. This may help.

I also added quotes around the executable and the file path of the active editors file in the external call to execute calculation.

**Comment by ghost** [comment]
Thank you, at the end surrounding the quotes to absolute path brings up an error (double quotes, as you already quote the variable right), but with your fix, it works perfectly using double backslash for the absolute path now.
Thanks!
